var annotated_dup =
[
    [ "_funmap", "struct__funmap.html", "struct__funmap" ],
    [ "_hist_entry", "struct__hist__entry.html", "struct__hist__entry" ],
    [ "_hist_state", "struct__hist__state.html", "struct__hist__state" ],
    [ "_keymap_entry", "struct__keymap__entry.html", "struct__keymap__entry" ],
    [ "area", "structarea.html", "structarea" ],
    [ "cercle", "structcercle.html", "structcercle" ],
    [ "COMMAND", "struct_c_o_m_m_a_n_d.html", "struct_c_o_m_m_a_n_d" ],
    [ "command", "structcommand.html", "structcommand" ],
    [ "curve", "structcurve.html", "structcurve" ],
    [ "layer", "structlayer.html", "structlayer" ],
    [ "line", "structline.html", "structline" ],
    [ "list_", "structlist__.html", "structlist__" ],
    [ "lnode_", "structlnode__.html", "structlnode__" ],
    [ "pixel", "structpixel.html", "structpixel" ],
    [ "pixel_tracer", "structpixel__tracer.html", "structpixel__tracer" ],
    [ "point", "structpoint.html", "structpoint" ],
    [ "polygon", "structpolygon.html", "structpolygon" ],
    [ "readline_state", "structreadline__state.html", "structreadline__state" ],
    [ "rectangle", "structrectangle.html", "structrectangle" ],
    [ "shape", "structshape.html", "structshape" ],
    [ "squar", "structsquar.html", "structsquar" ],
    [ "undo_list", "structundo__list.html", "structundo__list" ]
];